# settings.yml
site:
  title: "IDSA Landscape"
  favicon: "/images/favicon.ico"

header:
  logo: "/images/idsa_logo.svg"
  logo_link: "https://github.com/International-Data-Spaces-Association"
  logo_height: "40"

colors:
  primary:   "#0066CC"
  secondary: "#004499"
  tertiary:  "#E0F2FF"
  accent1:   "#0099FF"
  accent2:   "#003366"
  accent3:   "#0055AA"
